### ISSUE TITLE
[V3 Embed Maker: ability to have the embed dm/dmglobal command dm to the user who called it

### ISSUE THREAD

**Issue by kennnyshiwa** [mikeshardmind/SinbadCogs#103]
Users should be able to call the embed dm/dmglobal command and have it fill in the users ID which then Dm's them the embed. Currently you have to manually specify the user's id/name to have the embed set which does not work if you want to have the embed set as an alias and called by users to have a embed sent to them. 

create dmglobal embed
set alias that calls this dmglobal embed
and then when the alias gets called it shoots that person the dm

**Comment by mikeshardmind** [comment]
Context:
![image](https://user-images.githubusercontent.com/22035876/52731689-55079d00-2f8c-11e9-9ffb-7c65ecacd7c6.png)
