### ISSUE TITLE
Code cleanup

### ISSUE THREAD

**Issue by mikeshardmind** [mikeshardmind/SinbadCogs#109]
The recent issue with:
d82e9fa and the subsequent fix 2a27e1a shows how fragile some old workarounds in the code are with regard to modifications.

At some point, the entire existing code needs to be stripped of any no-longer necessary workarounds.

This was a fragile conversion that broke in an unexpected way due to a "quick fix", when it should have been replaced with the more robust Union converters the moment the repo was no longer supporting a red version which did not have access to those.

There are definitely more things like this in the code which should be handled before they cause the next issue where a small change has unexpected side-effects.

**Comment by DiscordLiz** [comment]
I've done some of the initial pass.

as of 3b3dd2cc18d37394a66f69138475b3f49c176ded
Antimentionspam is ready now if you get the chance to begin looking at changes @mikeshardmind
