### ISSUE TITLE
[V3][RoleManagement] Removing reaction does nothing

### ISSUE THREAD

**Issue by fixator10** [mikeshardmind/SinbadCogs#111]
If i understand correctly, this code:
https://github.com/mikeshardmind/SinbadCogs/blob/258bb4b205f5a52405e84ab8690e8302572030b8/rolemanagement/events.py#L78-L101

Must remove role on removing of reaction. But this is not happens.
![](https://Moeka.is-a-good-waifu.com/6qwyM7C.png)
![](https://Moeka.is-a-good-waifu.com/5rMg2kd.gif)

**Comment by mikeshardmind** [comment]
You need to set the role as self-removable for removing a reaction to remove the role:

![2019-02-24_09-53-35](https://user-images.githubusercontent.com/22035876/53300853-518cd500-381a-11e9-8c0f-ba3858b28340.gif)
