### ISSUE TITLE
[Bug] Roomtools

### ISSUE THREAD

**Issue by lionirdeadman** [mikeshardmind/SinbadCogs#118]
If you keep switching voice channel, it seems to sometimes delete the original voice channel and then it doesn't clone anymore.

**Comment by mikeshardmind** [comment]
What exactly are you requesting as a feature here?

Keep in mind that 

1. The temporary or automatic channels *should* be removed when empty
2. That there's a bit of an antispam measure in there to prevent users from killing the bot with rate limits

**Comment by lionirdeadman** [comment]
Yeah, writing issues at 4AM is not the best idea, I meant that it was a bug.

Trying to join that same voice channel that 'broke' yesterday works so it is probably the antispam features kicking in (I didn't know they were there) so I can close this.
