### ISSUE TITLE
[V3 Scheduler] Cancel task from [p]showscheduled menu

### ISSUE THREAD

**Issue by jack1142** [mikeshardmind/SinbadCogs#119]
Like in title, I think it would be useful to be able to cancel/unschedule task from the menu which shows when you use `[p]showscheduled` or `[p]scheduleradmin viewall`:
![Discord_2019-03-17_18-36-23](https://user-images.githubusercontent.com/6032823/54495417-b8fee780-48e3-11e9-8e17-9bb438def728.png)

**Comment by mikeshardmind** [comment]
Blocked by #122
