### ISSUE TITLE
[V3 AntiMentionSpam] write to modlog

### ISSUE THREAD

**Issue by fixator10** [mikeshardmind/SinbadCogs#121]
Currently, AntiMentionSpam does not writes case in modlog when mutes/bans for mention spam

**Comment by mikeshardmind** [comment]
Currently it relies on Red's builtin unclaimed case detection. There's an open issue which will allow more flexibility with this in a way I'm willing to do.

**Comment by mikeshardmind** [comment]
As of Cog-Creators/Red-DiscordBot#2901 this can feasibly be added.

However, as it's a large breaking change, this won't be added until the 3.2 release of Red. I'll package together the required changes for this and other planned breakage later.
