### ISSUE TITLE
[Scheduler] wrong timezone parsing

### ISSUE THREAD

**Issue by fixator10** [mikeshardmind/SinbadCogs#127]
Timezone seems to be parsing incorrectly

When i pass SAMT as timezone (Samara Time, UTC+4, my local timezone on screenshots), it schedules as 8AM UTC, instead of 12AM
![+8hours?](https://Moeka.is-a-good-waifu.com/4Staj8e.png)

When i dont pass timezone, its just adds 4 hours of time to task
![+4hours](https://Moeka.is-a-good-waifu.com/12D5ujk.png)

Server's time is UTC-5
![UTC-5](https://Moeka.is-a-good-waifu.com/2pMwrQX.png)

**Comment by mikeshardmind** [comment]
Superseded by work to move this into core Red
