### ISSUE TITLE
Limit users for new temp channels

### ISSUE THREAD

**Issue by hacklover** [mikeshardmind/SinbadCogs#130]
Can you also implement the possibility to limit number of users for new temp channels?
Maybe using a parameter like `-u 2` at the end of !tmpc

**Comment by HelmicNewciv** [comment]
Temporary channels mimic the settings and permissions of the original channel.  Go to the original channel's settings -> Overview -> under User Limit, set it to the desired maximum.  That should accomplish what you want and makes it easy to adjust it later, as well as communicating to users how many users are permitted in each channel even if all channels are empty.
