### ISSUE TITLE
[EmbedMaker] Allow editing of existing embeds

### ISSUE THREAD

**Issue by Mystard** [mikeshardmind/SinbadCogs#131]
Kind of a two-parter feature request:

1. Allow editing of already dropped embed messages. This has been suggested a few times on Discord, saw some suggestions to just allow dropping a new embed with message ID so the new drop would replace the content of the old message.

2. Allow updating saved embeds. This is my own additional request, would eliminate the need to remove and then create the embed again.

**Comment by DiscordLiz** [comment]
unless @mikeshardmind has a reason against it, I'll work on both of these.

**Comment by mikeshardmind** [comment]
I have concerns about editing already dropped messages without storing something to identify who sent something. Updating saved embeds was planned already.

**Comment by Mystard** [comment]
Well my personal need for the editing of already dropped embeds is as follows:

I have an embed set that tells about user obtainable roles, and on that message I have react_roles set up so users can look at the embed's list and read info about the user obtainable roles and then gain and remove them by reacting. These are roles for certain games that groups of people play, so every time I need to add a new role to the embed's list I can just edit it with caleb's embedwiz (using my V2 instance for this still).

My plan is to move this functionality to my V3 instance and get rid of V2, but atm I can't because I can't edit the embeds. If I need to redrop the embed, I also have to redo my entire react_roles setup every time, which is highly inconvenient.

I can see the reasoning why you don't want to implement it without the additional storing of who posted which embed, but if it's possible to implement this functionality that would be great.

**Comment by mikeshardmind** [comment]
After giving this some thought, there will be a setting to enable a command for changing the embed in a previously posted message. The command will be limited to admins when enabled (further restrictable/allowable with permissions)

The ability to edit existing embeds (not messages, the stored embeds) will be limited to the original author or admins.

**Comment by mikeshardmind** [comment]
Part of this is in (editing the embeds of existing messages)

The second part (editing saved embeds) is planned, but not being worked on yet.

**Comment by mikeshardmind** [comment]
[Won't be added](https://github.com/mikeshardmind/SinbadCogs/blob/v3/why_no_support.md)
