### ISSUE TITLE
[V3.1 AntiMentionSpam] Mute creates perms overwrites incorrectly (?)

### ISSUE THREAD

**Issue by fixator10** [mikeshardmind/SinbadCogs#135]
So... Mute creates overwrites, that doesn't get deleted on unmute if overwrite is empty

Expected behavior: as in `[p]mute server <user>` and then `[p]unmute server <user>` if user was not in channel's permissions overwrites - overwrite removed
![unmute after Mod's mute](https://Moeka.is-a-good-waifu.com/73ePNB9.png)
Actual behavior: after antimentionspam's mute, on `[p]unmute server <user>` overwrites still exists even if empty
![unmute after antimentionspam](https://Moeka.is-a-good-waifu.com/7TeLrRE.png)

**Comment by mikeshardmind** [comment]
Will verify this later, but this should be fixed for the patch for this on 3.1 if it is this cog causing it.

**Comment by mikeshardmind** [comment]
This is an issue with red's unmute command, not with this cog.
