### ISSUE TITLE
[RoleManagement] Roleset viewrole should tell if role is buyable and it's cost

### ISSUE THREAD

**Issue by Mystard** [mikeshardmind/SinbadCogs#142]
I think it would be useful if `[p]roleset viewrole <role>` also showed if the role in question is buyable, and what it costs.

At the moment there is no way to see role costs, right? This would fix that.

**Comment by MisterInsane** [comment]
To add on to this, it should also show if the role is sticky. Might as well if we're showing all role settings, right?
