### ISSUE TITLE
[RSS] Creating channels via rss feed.

### ISSUE THREAD

**Issue by xSignificant** [mikeshardmind/SinbadCogs#145]
Allow the RSS feed to create a new channel when there's a new item and have the cog delete the channels after a specific amount of time has passed.

Could be useful to people that would like to have discussions of the item being posted.

**Comment by mikeshardmind** [comment]
This is very out of scope for RSS as a cog. While I may add some event dispatching for other cogs to use later on, I have zero intention of adding this particular behavior to the cog.

**Comment by mikeshardmind** [comment]
There's a versioned event dispatch that other cogs could use to accomplish this now, but the behavior itself won't be added.
