### ISSUE TITLE
[AntiMentionSpam] Mute using role

### ISSUE THREAD

**Issue by jack1142** [mikeshardmind/SinbadCogs#147]

**Comment by mikeshardmind** [comment]
If we assume the planned additions for Red's core mute are added, would it be sufficient to have a setting to invoke `mute server` against the user for your use case here? I'd rather this be allowed to invoke other things, even with pre-filled extra parameters if needed than to grow the mute logic by much here.

**Comment by jack1142** [comment]
Yes, it would be enough for my use case, I kinda had those changes in mind while creating this issue.

**Comment by DiscordLiz** [comment]
I'll work on the changes for this after I finish the mute rewrite for Red.

**Comment by mikeshardmind** [comment]
[Won't be added](https://github.com/mikeshardmind/SinbadCogs/blob/v3/why_no_support.md)

**Comment by DiscordLiz** [comment]
Mute has gone nowhere in core. I don't want to do it anymore. The PR open doesn't do anything for an API. I'll add a role setting.
