### ISSUE TITLE
[feature] Add warn system cog API

### ISSUE THREAD

**Issue by Skyrid3r** [mikeshardmind/SinbadCogs#153]
Is there anyway the following API can be included?

https://laggron.red/warnsystem-api.html#warnsystem.api.API.warn

Regards,
Skyrider

**Comment by mikeshardmind** [comment]
No. I'm happy to add support for any core red APIs or add a dispatch for certain events for other people to use without needing to rely on the cog being loaded, but I'm not going to attempt to detect other 3rd party code and interact with it as this would be an ever expanding goal as more 3rd party cogs do similar things.

**Comment by Skyrid3r** [comment]
@mikeshardmind 

I apologize, and I understand if you still don't wish to add it as I wasn't specific enough regarding the warnsystem cog. The only reason why I was suggesting this is because the warnsystem includes a kick/ban/warn system under different command lines, which in my opinion is better over the core kick/ban/warn functions.

**Comment by mikeshardmind** [comment]
>The only reason why I was suggesting this is because the warnsystem includes a kick/ban/warn system under different command lines, which in my opinion is better over the core mod functions especially checking user history wise.

If you consider that system better, I suggest you open feature requests to Red for what you want from it. 

And to be entirely clear: 

Cogs which depend on other Cogs which can't be guaranteed to be available are a very shaky tower which I'm not willing to contribute to. 

Even if I were to take a pessimistic, defensive approach while doing so (which could be done safely), I'd then be opening up to other requests for additional APIs beyond that. 
Then if I denied those, having to justify why I'd support one over another. 

I'd prefer to circumvent that process entirely and have the core API improved.
