### ISSUE TITLE
[RSS] Include Image 

### ISSUE THREAD

**Issue by efinst0rm** [mikeshardmind/SinbadCogs#155]
Hi,
Is it possible to include the image from the description field so it can show up in the embed.

Looking to do something like this.
![xIKe1gu](https://user-images.githubusercontent.com/7751074/61847203-6cb64c00-ae6f-11e9-9377-43c1699a17c3.png)

Thanks

**Comment by mikeshardmind** [comment]
[Won't be added](https://github.com/mikeshardmind/SinbadCogs/blob/v3/why_no_support.md)
