### ISSUE TITLE
[RoleManagement] Multiple binds to a reaction

### ISSUE THREAD

**Issue by MK99MA** [mikeshardmind/SinbadCogs#156]
First of all, thank you for creating the cog and sorry if I missed any of the following mentioned functionalities.

I'm currently using the RoleManagement Cog on a public server combining different subcommunities of one CS:S / CS:GO mod. Therefore people can request roles based on their area (Eu, Rus, Na, Sa) as well as the games (CS:S, CS:GO).

At the moment people should first request their area role and following that a game for their role. However since CS:S EU and CS:S NA, for example, are divided (Having the CSS EU role enables its category, CSS NA enables another one), we have to create a new reaction message for each area giving the respective variant of the gamerole.
Ideally people would choose their desired area-role and after reacting with the css reaction get every css role depending on their area roles (Person A got the roles for EU and RUS so reacting with the CSS reaction would grant him the CSS EU and CSS RUS roles)

I don't know if it is possible at all, but with the possibility of creating requirements for roles it didn't seem too farfetched to be possible.

Another aspect I wanted to ask about regarding the cog is the possibility to remove a requested role by removing the reaction from the message. I'm aware that there is a command to do so, I just thought if adding a role by reacting is possible, removing it by removing the reaction again would be possible too.

Thanks in advance for any reply.

**Comment by flaree** [comment]
To answer 
>Another aspect I wanted to ask about regarding the cog is the possibility to remove a requested role by removing the reaction from the message. I'm aware that there is a command to do so, I just thought if adding a role by reacting is possible, removing it by removing the reaction again would be possible too."

You can set the role as self removable using the `[p]roleset selfrem` command.

**Comment by MK99MA** [comment]
> To answer
> 
> > Another aspect I wanted to ask about regarding the cog is the possibility to remove a requested role by removing the reaction from the message. I'm aware that there is a command to do so, I just thought if adding a role by reacting is possible, removing it by removing the reaction again would be possible too."
> 
> You can set the role as self removable using the `[p]roleset selfrem` command.

Thank you for your reply. 
Indeed I didn't notice the command, or rather didn't look further into it as I thought it would only control the roles that are removable by "[p]srole".

Again, thank you for your reply.

**Comment by mikeshardmind** [comment]
This will require a change to the data structure which is in use for role management currently.

I intend to add support for this and a few other non-standard configurations, but will depend on my availability as to when I will have enough time to get to this one.

**Comment by mikeshardmind** [comment]
[Won't be added](https://github.com/mikeshardmind/SinbadCogs/blob/v3/why_no_support.md)
