### ISSUE TITLE
Scheduler Mk II

### ISSUE THREAD

**Issue by mikeshardmind** [mikeshardmind/SinbadCogs#159]
Okay, so with the knowledge of the current scheduler's shortcomings around DST *transitions*, and the intent to offer the cog as a core cog once ready, scheduler needs to be next up for major improvements.

Planned:

 - Timezone name storage (not offset) with pytz lookup
 - DST transition handling with pytz's localize
 - Improved handling of task scheduling, canceling.

**Comment by mikeshardmind** [comment]
There are some fundamental changes required of this that lead me to believe the time is better spent on a generalized sceduler api and minimal frontent for it.

**Comment by DiscordLiz** [comment]
Can I convince you to pick this one back up?
