### ISSUE TITLE
[RSS] Suggestion: Filter

### ISSUE THREAD

**Issue by Menteroth** [mikeshardmind/SinbadCogs#160]
Would it be possible to add a feature that filters YouTube uploads through the title? Like adding Gran Turismo Sport for instance, to a whitelist. So it doesn't post stuff that doesn't have that in the title.

**Comment by mikeshardmind** [comment]
[Won't be added](https://github.com/mikeshardmind/SinbadCogs/blob/v3/why_no_support.md)
