### ISSUE TITLE
[antimentionspam] log to modlog

### ISSUE THREAD

**Issue by kennnyshiwa** [mikeshardmind/SinbadCogs#161]
When muting the user currently no mod log case is created, it would be nice to see a modlog case created for when they are muted since i would assume most use the ``[p]unmute`` command to unmute them which does generate a modlog case so it looks odd as it appears they get unmuted for no reason lol

**Comment by mikeshardmind** [comment]
Changes required for this already exist (90975d0) on the branch where I'm incorporating things to be merged when Red 3.2 is available.

**Comment by kennnyshiwa** [comment]
sounds good, i had thought of this before and forgot so figured i would write it down so i didn't forget again

**Comment by mikeshardmind** [comment]
Also, closing, duplicate #121
