### ISSUE TITLE
[RoleManagement] What's next?

### ISSUE THREAD

**Issue by mikeshardmind** [mikeshardmind/SinbadCogs#166]
- Multiple roles to a reaction / removals allowed to adding a reaction #156 
- More rules for allowed additions and removals
  - Limit removal to still maintaining a specific minimum
  - Add more options on maximums
  - Add some automatic additions/removals based on specific other criteria

**Comment by mikeshardmind** [comment]
This is probably gonna be larger than it looks at a glance on the changes.

Requires rewriting a few significant sections while retaining as many optimizations as possible.

As far as when this can be expected, it will *not* exist prior to 3.2 of Red
I intend to use a few things in that to make this happen more sanely.

**Comment by mikeshardmind** [comment]
Progress update on each of: 
  - #156 (multiple actions to a reaction)
  - Limit removal to still maintaining a specific minimum
  - Add more options on maximums
  - Require being in the server for a specific amount of time prior to getting a role
  - Allow reactions to remove roles (vice versa as well)

These will be using things added in Red 3.2
I hope to have all three of them ready shortly following the 3.2 Release.

The following won't be ready at the same time, but are still planned:

 - Add some automatic additions/removals based on specific other criteria
 - Reaction traps (RE: evolving spammers)
 - Notifications on specific actions.

**Comment by mikeshardmind** [comment]
[Work on this abandoned](https://github.com/mikeshardmind/SinbadCogs/blob/v3/why_no_support.md)

**Comment by DiscordLiz** [comment]
Of what you didn't do there, can we add

- [ ] Require being in the server for a specific amount of time prior to getting a role
- [ ] Limit removal to still maintaining a specific minimum
- [ ] Add more options on maximums

back on the plan?
