### ISSUE TITLE
[RSS] I Can't Recall It Being Like This Before

### ISSUE THREAD

**Issue by Menteroth** [mikeshardmind/SinbadCogs#181]
The ones saying 'broken feed' are just in another channel. And they are shown as normal when you list using the channel. I can't remember it being like this before.

![image](https://user-images.githubusercontent.com/24851042/69903483-2da68300-139a-11ea-89ae-434e82a7b2ce.png)

**Comment by mikeshardmind** [comment]
Can't reproduce this issue, I'm only seeing feeds for the current channel.
