### ISSUE TITLE
[EmbedMaker] Support advanced templating (e.g. use set parameters passed to command)

### ISSUE THREAD

**Issue by jack1142** [mikeshardmind/SinbadCogs#182]
Stuff that could be part of this (just putting all thoughts, not all of this may make sense to spend dev time on or it may not be a good idea at all):
- all the stuff CustomCommands cog can do (Context Parameters and Command Parameters sections in [here](https://docs.discord.red/en/latest/cog_customcom.html#command-parameters))
- access to current timestamp (i.e. `datetime.datetime.now()` object), or maybe even better, just access to whole `datetime` object - for example adding/subtracting `timedelta` from current time could come useful (`jinja2`)
- conditional statements (`jinja2`)
- support for `*args` and `*, consume_rest`?

And you said that it might be good to make it dependent on [red#3163](https://github.com/Cog-Creators/Red-DiscordBot/issues/3163) so putting that thought here as well.

**Comment by mikeshardmind** [comment]
I have some long term ideas on this which I didn't try to spell out in detail with the current issues with Discord's responsiveness (or lack thereof)

I'll be looking to allow safe access to certain things from the invocation context.

I'm unsure if I want to support args to this yet, and may need to give handling this more thought, as whatever converters are exposed for this need to only return formatting safe objects.

If supporting args, I may take the time to first make the formatting safe converters for work upstream in core Red, then utilize them myself for EmbedMaker as well.

Either way, these ideas are all floating on my radar right now and are just waiting to be handled at a point where all prior necessary work is done, and I have time available to handle it.

**Comment by mikeshardmind** [comment]
[Won't be added](https://github.com/mikeshardmind/SinbadCogs/blob/v3/why_no_support.md)
