### ISSUE TITLE
Bug in scheduler

### ISSUE THREAD

**Issue by Dav-Git** [mikeshardmind/SinbadCogs#184]
Scheduler is not executing the scheduled commands. They still show up in [p]scheduleradmin viewall and the logs show nothing out of the ordinary.

How to reproduce? No clue.

**Comment by mikeshardmind** [comment]
I can't reproduce this with even just a minimal test. I'll need more information to look into this.

![image](https://user-images.githubusercontent.com/22035876/71389540-ca8bc300-25ca-11ea-8571-7fbde692235c.png)

**Comment by Dav-Git** [comment]
Through magic it started working again. No clue. It's a Christmas miracle.
