### ISSUE TITLE
[BanSync] Option to Specify Which Servers to Sync

### ISSUE THREAD

**Issue by LGACode** [mikeshardmind/SinbadCogs#185]
Please add an option to specify which servers to sync bans instead of just syncing bans across all servers that the bot is in.

**Comment by mikeshardmind** [comment]
Already exists. See the `syndicatebans` command

Additionally, the `bansync` command only syncs all servers without selection if you give it a "yes" for the auto parameter (otherwise, it prompts for which servers to sync)
