### ISSUE TITLE
[Relays] Mode for webhooks

### ISSUE THREAD

**Issue by mikeshardmind** [mikeshardmind/SinbadCogs#186]
The initial reason against this was impersonation confusion, however, since the original stance, webhooks got a [bot] tag from Discord. (IMO, this should have always been the case, but I digress)

Making such a change will allow forwarding messages as-is (or mostly as-is) including messages from (other) bots that were embedded.

**Comment by thisisjvgrace** [comment]
I would die for this feature. This would be really awesome to have from user experience point of view. Please implement this when you can! and thank you once again for providing all these productive awesome cogs.

**Comment by mikeshardmind** [comment]
[Won't be added](https://github.com/mikeshardmind/SinbadCogs/blob/v3/why_no_support.md)
