### ISSUE TITLE
[EMBED MAKER] Suggestion | Pages

### ISSUE THREAD

**Issue by Menteroth** [mikeshardmind/SinbadCogs#187]
So when creating an embed it would be great to be able to decide how much would be inside an embed before adding reactions to see more pages you can look through. Just like using `help` command with the `usemenus` option for Red's help.
Then one could create their own help embeds for custom commands and the embed wouldn't endup being one long embed when enough command descriptions have been added.

**Comment by mikeshardmind** [comment]
The closest to this I intend to support is #134 People can handle their own content lengths, I don't intend on modifying provided embeds for people, and consider it to be out of scope for embedmaker.

I may reconsider this in the future.
