### ISSUE TITLE
[RoleManagement] Add ability to mass kick everyone in a role

### ISSUE THREAD

**Issue by LGACode** [mikeshardmind/SinbadCogs#189]
Please add a command in RoleManagement that would allow someone with the correct permissions to kick everyone in a specific role.

This is useful when combo'd with Scheduler to regularly clean out an "Unverified" role that is automatically assigned to new people.

**Comment by mikeshardmind** [comment]
I have some reservations about adding this, but It's not a "no". 

I need to think about how I would want to implement this, and if it can reasonably coexist with the other features of the cog, and the bot's permission model.

It's a relatively low priority, but if I decide I can accommodate it, it won't take me long to do so and could be bumped up to the top priority wise.

**Comment by Brandjuh** [comment]
I can use this function as well. But also in a reversed way, people without a specified role or without anyrole.

**Comment by mikeshardmind** [comment]
I can't add this. I've given it a lot of thought but taking mod actions on an entire role doesn't seem the sort of action I support. There may be a need for cases where people are unverified for a while, but these require more info than my cog will ever support interacting with. The only cases which this would not lead to abusive at best behavior are better suited by other tools tailored to the purpose.
