### ISSUE TITLE
[IDEA] Report/Suggestionbox cogs

### ISSUE THREAD

**Issue by MidnightMafia** [mikeshardmind/SinbadCogs#19]
I think a cool feature to add, would be for suggestion and reports, to give them an ID#, and staff that recieve these suggestions/reports, can respond directly to the user with the given ID, through the actual bot.

Example:

User A submits a report, with a report # of 1.

Then the staff team, can do [p]respond {ID#} {response}

This way, the report/suggestion can be replied too directly, straight through the bot. 

Feel free to comment below and questions, or need a better explanation.

**Comment by mikeshardmind** [comment]
I'd like to make this happen, but my current priority is fixing any major bugs found and having all of the code ready for the release of Red v3. Good news is I am almost done with the latter.

**Comment by mikeshardmind** [comment]
Update: This will be a feature of the version of the cog released for red v3 (when that happens)
