### ISSUE TITLE
[RSS] Have both content and embed in message

### ISSUE THREAD

**Issue by jack1142** [mikeshardmind/SinbadCogs#195]
**Is your feature request related to a problem? If so, Please describe.**
Basically I want both of these at the same time:
a) the bot should ping me on new post in feed
b) the bot should show the post's data in embed using set template
Example:
![image](https://user-images.githubusercontent.com/6032823/72855007-638b2800-3cb6-11ea-83f0-f0419e0c4503.png)

**Describe the solution you'd like**
Possibility to set a template for both message's content and embed and new option in `[p]rss embed` that would allow me to have both enabled at the same time.

**Describe alternatives you've considered if any**
I don't have any alternatives in mind.

**Comment by mikeshardmind** [comment]
I won't put any time into this myself, but I don't have an issue with it being added if someone does it.

**Comment by mikeshardmind** [comment]
[Won't be added](https://github.com/mikeshardmind/SinbadCogs/blob/v3/why_no_support.md)
