### ISSUE TITLE
[RSS] `[p]rss template` doesn't verify if passed feed exists

### ISSUE THREAD

**Issue by jack1142** [mikeshardmind/SinbadCogs#196]
**Describe the bug**
`[p]rss template <feed> [channel] <template>` doesn't have any verification if feed passed in `<feed>` exists.

**Comment by mikeshardmind** [comment]
Not sure if I want to consider this a bug, as I don't actually care if people set a template prior to the url and it's less config calls. I probably should just to prevent some potential confusion though.
