### ISSUE TITLE
[RoleManagement] Subcommand for ordered list of reaction roles

### ISSUE THREAD

**Issue by synrg** [mikeshardmind/SinbadCogs#203]
The manual setup cost of a reaction role menu goes up as the reaction list length increases. For longer and/or more frequently edited reaction role menus, this can grow to be quite burdensome, particularly if a menu is both long and frequently edited. For example, consider an embed as follows.

```
-embed advmake location-na
title: Choose your location
description: React to choose your location(s) of interest.
  **1**=Texas **2**=Midwest **3**=Mid-Atlantic **4**=California 
  **5**=Ontario **6**=Maritimes **7**=Great Plains **8**=Southeast 
  **9**=New England **10**=Rocky Mountains **A**=Great Lakes 
  **B**=Florida **C**=Desert Southwest **D**=Pacific Northwest 
  **E**=Canadian Prairies **F**=Quebec
```

We would like to be able to edit/reorder the roles list for such an embed in a single command rather than having to unbind all of the roles one at a time that are affected by such reordering, then add them back one at a time. My initial idea for an interface would be this, though you might think of a better way.

```
-rolebindmulti #info 675404009929965568 Texas :one: Midwest :two: Mid-Atlantic :three:
  California :four: Ontario :five: Maritimes :six: "Great Plains" :seven: Southeast :eight:
  "New England" :nine: "Rocky Mountains" :keycap_ten: "Great Lakes" :regional_indicator_a:
  Florida :regional_indicator_b: "Desert Southwest" :regional_indicator_c:
  "Pacific Northwest" :regional_indicator_d: "Canadian Prairies" :regional_indicator_e:
  Quebec :regional_indicator_f:
```

As a workaround, we are keeping a document with all of the commands needed to add/remove these roles so that mods can edit them there, then cut-and-paste them one at a time to make changes.

**Comment by mikeshardmind** [comment]
So this has sort have been on the "do this eventually" list for a while now. There are two ways I can see it functioning, and I'm still unsure which one ends up better.

1. It's only a bulk command, it doesn't remove existing binds on a message.
  - This would come with an additional command to clear all binds from a message
2. It's a command which automatically clears existing binds on a message before creating the provided ones.

Thre are some minor tradeoffs between the two which mostly come down to implementation detail as far as I've considered so far and I don't have a strong preference either way. 

This is part of why I've been so hesitant around actually doing it. I figured if I was apathetic about which way of doing it, I may not have considered something important about how it should function.

**Comment by synrg** [comment]
You might want to "batch up" your updating effort bulk add several roles at once, which favours approach 1. It's not that big of a deal to have to type another command first when you really want to clear all the binds first. That's my *very slight* preference. I'd be happy with it either way, though, if you don't feel that use case is worth deliberately supporting. Re-doing them all at once might be what people expect, and they don't appreciate having to do an extra step first (which they might forget).

**Comment by mikeshardmind** [comment]
Eh. I'm leaning toward the first as it has more uses (even in just adding more to an existing set), with a warning if there's any binds already existing at the start. The latter is just something I'm expecting will end up how more people actually use it.

**Comment by Dav-Git** [comment]
I actually support 1 over 2. I don't think the bot should do something it doesn't get told to do and adding reactions to a message via command is the expected behaviour of the cog at this point. If your list of roles is very long (if someone somehow managed to break through the 2000 char barrier) it would be easier for them to add 2 bulks in 2 commands rather than adding one in bulk and the rest manually because otherwise the first batch would be cleared.
