### ISSUE TITLE
[RoomTools] Text Channels

### ISSUE THREAD

**Issue by ibigfire** [mikeshardmind/SinbadCogs#207]
**Is your feature request related to a problem? If so, Please describe.**
When I grabbed RoomTools I was thinking it would be useful to create text channels for temporary topics and subject.  A recent game or movie or the like, that some people may want to discuss openly but others would want to avoid due to spoilers and the like.

**Describe the solution you'd like**
Expand RoomTools to also offer options for temporary text rooms instead of solely voice ones.

**Additional context**
If it's difficult to implement then don't worry about it or anything.  The tool is super duper useful as is and I love your cogs you provide for free already.  Thank you creating them and keeping them working and such.  Really appreciated!

**Comment by mikeshardmind** [comment]
I'm glad you've found this useful!

I've considered text channel support a few times, but each time there were various issues with allowing it.

1. Allowing the user to own the channel could be dangerous, many checks in red are based permissions in a channel.

2. The cog would need to track more data to determine when a channel should be closed, and criteria for closing would vary more than with voice channels among various use cases.
