### ISSUE TITLE
Location awareness with Quotetools.

### ISSUE THREAD

**Issue by pixelrepublic** [mikeshardmind/SinbadCogs#211]
When using Quotetools, I have to specify the channel I want the quote in. However, If I run the command in #channel-one, while quoting a message in #channel-two. It won't work.

I get the message:
> No matching message found.

I can only run the command, in the channel the quoted message originates from. But I'm still required to specify the channel.

Seems silly.

**Comment by mikeshardmind** [comment]
Quoting other channels works just fine.
