### ISSUE TITLE
roleset: selfassignable roles via ractions limited to the 10 lowest privileged roles

### ISSUE THREAD

**Issue by xTamee** [mikeshardmind/SinbadCogs#216]
Describtion:
After I tried setting up some self assignable roles I noticed, that only the 10 lowest privileged Roles could be self assigned by reacting to a message.

The self assignable roles were created like the following:
[p]roleset selfadd @ROLE yes
[p]roleset selfrem @ROLE yes
[p]rolebind @ROLE #CHANNEL {TEXT-ID} :EMOJI:

after setting up 12 roles like this, I noticed that I could only get 9 roles.
The lowest privileged role is @everyone which I did not add as self-assignable.
After @everyone the next 9 roles worked perfectly, BUT I have 12 roles which I need to be self-assignable, unfortunately the 3 missing roles don't work.

I get the following error message:
"Can't do that. Discord role heirarchy applies here."

Any info about that? Any possible Fix?

**Comment by mikeshardmind** [comment]
I can't reproduce this as an actual issue. (caveat below)

That error message should only be encounterable if the attempted layout would cause an issue.

There are two (caveat below applies to this) ways in which this message can be encountered (per role)

1. You are not the guild owner and the role is not below your top role
2. The bot is not the guild owner and the role is above the bot's top role

The way in which this could be broken is if there's an issue with the member role cache. I've heard reports of people ending up with a bad member role cache, but this would be an issue with discord.py, not the cogs here. With that said, if this is the issue, a bot restart will resolve it short term.

**Comment by xTamee** [comment]
First, thanks for your fast response.

Actually I am the guild owner, also the bot has administrative rights and is the 2nd highest role on the guild.
The role hierarchy is like the following:
1 Guild leader
2 Bot
3 Member
4 Not working assignable role
5 Not working assignable role
6 Not working assignable role
7 Working assignable role
8 - 16 Working assignable role
17 Everyone

I also tried restarting the bot already, did not fix it.

**Comment by mikeshardmind** [comment]
With that additional information, I went to double-check the code path. There is one other way in which this can fail with that specific message. There are a handful of types of roles that are considered "managed" roles. These include the twitch partnership integration for subscribers in a streamer's discord and the role tied to nitro boosting. Bots can't assign those.

If you can confirm that none of those three should fall into that, I'll take a closer look at this when I have the time today.

**Comment by xTamee** [comment]
Ok, so I restarted the bot, and restarted the whole server, on which the bot is running, and somehow it works now.
Guess you were right with the cache issue.

Thanks for your suggestions and help.

(None of the roles I used for self assign were managed roles) - just for info ^^

Closed

**Comment by mikeshardmind** [comment]
Since a restart fixed it, I'm definitely leaning towards this being a cache issue. I'll ask around about this and see if I can help handle this one upstream since I'm pretty sure I've seen this cause an issue before, and it's impacting the cogs.
