### ISSUE TITLE
RSS cog doesn't handle XHTML breaks

### ISSUE THREAD

**Issue by joshuacant** [mikeshardmind/SinbadCogs#217]
Hi, line 6 of /rss/cleanup.py needs to read:

`WhitespaceHandler = re.compile("<p>|<br>|<br />|<li>", flags=re.MULTILINE)`

in order to handle converting the xhtml `<br />` tag into a newline.

Thanks for the cogs, and sorry this isn't a PR, but it's 7 characters.

**Comment by mikeshardmind** [comment]
Hey, thanks for spotting that!

The help's appreciated in any reasonable form, and I've gone ahead and marked you as a co-author of the commit fixing this (4b8c306) 

Edit: commit was reapplied in (73d4194) as I bungled github's coauthorship feature.
