### ISSUE TITLE
RoleManagement - Reaction roles - Channel "728741130426122260" not found.

### ISSUE THREAD

**Issue by BlueSoD** [mikeshardmind/SinbadCogs#221]
**Describe the bug**
Reaction roles - Channel "728741130426122260" not found.
I use the command .rolebind <rolename> <ID from post> :emoji:
and then it says "Channel "728741130426122260" not found."
my bot has administrator and every permission possible in both server and channel permissions.

**Debug info**
Debug Info for Red
Red version
3.3.9
Python version
3.8.1 (64bit)
Discord.py version
1.3.3
Pip version
20.1.1
System arch
x86_64
User
red
OS version
Ubuntu 18.04
Python executable
/home/red/redenv/bin/python
Storage type
JSON

**Comment by mikeshardmind** [comment]
Channel not found messages are generated by discord.py, not this cog and are caused by not matching a channel where one is expected.
