### ISSUE TITLE
Rolemanagement - Cant remove a viewreaction 

### ISSUE THREAD

**Issue by BlueSoD** [mikeshardmind/SinbadCogs#222]
**Describe the bug**
I have 3 viewreactions that are for a post in a channel that no longer exists, when i try to remove them from the cog with ".roleunbind role msgid :emoji:"
it gives the green check mark, as if it has been removed.
But when checked with ".roleset viewreactions", it's still being listed.

**Debug info**
Debug Info for Red
Red version
3.3.9
Python version
3.8.1 (64bit)
Discord.py version
1.3.3
Pip version
20.1.1
System arch
x86_64
User
red
OS version
Ubuntu 18.04
Python executable
/home/red/redenv/bin/python
Storage type
JSON

**Comment by mikeshardmind** [comment]
The usage you've claimed to use here

> .roleunbind :emoji:

would result in a role not found message, additionally, I've tested this with messages that don't exist anymore, and it works fine 
![image](https://user-images.githubusercontent.com/22035876/86846655-2dc9d800-c079-11ea-91be-4528c64e663e.png)

**Comment by BlueSoD** [comment]
Darn i had the ”<” Surroundig msgid and so on.. didn’t show up in my message here.
The viewreactions still show up in my server.
As see in below printscreen.
![0CD4FA1E-6D50-4634-BB4F-D48F43E4A1DB](https://user-images.githubusercontent.com/28658999/86855377-7bb30000-c0ba-11ea-9c15-93b466fb57ec.jpeg)
