### ISSUE TITLE
[roomtools] ceased to function fully

### ISSUE THREAD

**Issue by wertolet3** [mikeshardmind/SinbadCogs#223]
**Describe the bug**
The channel is created, but the user does not move, and after exiting the channel is not deleted automatically.

**Debug info**
Debug Info for Red
Red version
3.3.9
Python version
3.8.2 (64bit)
Discord.py version
1.3.3
Pip version
20.1.1
System arch
x86_64
User
root
OS version
Ubuntu 20.04
Python executable
/root/redenv/bin/python
Storage type
JSON

**Comment by mikeshardmind** [comment]
Update your bot and restart, discord changed something, discord.py (and subsequently Red) were both updated to handle this.
