### ISSUE TITLE
roomtools, doesn't auto move and clean up.

### ISSUE THREAD

**Issue by cyberofficial** [mikeshardmind/SinbadCogs#225]
**Describe the bug**
When a user joins a room, the room tools dont clean up the voice channels
roomtools is updated to latest

![2020-07-10 16-15-04](https://user-images.githubusercontent.com/19499442/87198473-c0ac8180-c2c8-11ea-8323-c15018267c8f.gif)

**Debug info**
```
Debug Info for Red
Red version
3.3.10

Python version
3.8.1 (64bit)

Discord.py version
1.3.3

Pip version
20.1

System arch
x86_64

User
dbot

OS version
Debian GNU/Linux 9

Python executable
/dbot_shell

/Home/dbots2/bin/python

Storage type
JSON
```

**Comment by mikeshardmind** [comment]
There's a small delay built-in on deleting to prevent race conditions. If the room was created within a couple of seconds of being empty, it won't be deleted but should get cleaned up at the next voice update event that happens (room tools scans the created channels, not just the related channel to the specific voice update.)

**Comment by mikeshardmind** [comment]
If you can confirm this happens after a minute of creation (this is longer than the window, but is small enough to be viable for testing), I'll try and get more info about the cases this is occurring in, but I have not seen this issue with an up to date red beyond the small exception covered above, which still results in the cleanup happening.

**Comment by cyberofficial** [comment]
I tried what you said and waiting, after around 40 seconds, i got moved into the new channel, but the channel never cleared after leaving it few a minutes while making coffee.

So i did an extra thing and thinking it may just be my discord bot being slow, so restarted my bot, same effect, so i think it may be the discord server location, so switch from EU to US and the cog is working as intended.

I don't know the theory behind, but writing this now to inform you, didnt mean to waste time, just discord being discord and having api hickups. Seems to happen allot. Thanks for the semi help.

*edit* tried closing this thread but github tossing me a 500 error

**Comment by mikeshardmind** [comment]
Huh. Thank you for the additional information, I'll see if I can find out if there's a reason why the EU region might be being handled differently, there's nothing region-specific in the code, but Discord has had issues of this sort before. I'm going to leave this one open for now.

**Comment by mikeshardmind** [comment]
Anecdotally, I've heard there were some issues with the EU region for voice recently, but if there are not any details logged, I'm not going to be able to do much more here. I'll look into adding some additional places where logging can happen as needed. If you encounter this again, I'd be happy to take a look if there's any actionable information.

**Comment by jkoen1996** [comment]
>so switch from EU to US and the cog is working as intended.

I am on the EU Server aswell, and switched to US East worked for me i didn't think of that. Maybe the EU server is over populated and things are weird
it worked until today so came to make a report and seen someone else has made a post.

gifv of what i encountered 
![forgithub](https://user-images.githubusercontent.com/9482840/87214859-8362e680-c2fe-11ea-976b-db82249f49a6.gif)
