### ISSUE TITLE
Consider relicensing

### ISSUE THREAD

**Issue by mikeshardmind** [mikeshardmind/SinbadCogs#226]
Options around this are somewhat complex, relicensing requires I either remove contributions from those who don't agree, or get agreement.

Supporting the cogs has become a burden again because of people taking a permissive license, making modifications that could break the cog, and not doing the bare minimum to ensure that this does not become my problem.

To prevent any future problems, I may also need to add a CLA with signing. Currently being considered, will be discussing with a lawyer if I decide it is worth pursuing.

The issue serves as a notice that this is the intent and the reason behind it. Whatever license is decided on will leave this open to use, but no longer open to modification. If you have made a contribution and are not okay with this, feel free to comment in advance to discuss options, but relicensing to something less permissive will not happen without explicit consent or another handling from contributors.

**Comment by DiscordLiz** [comment]
My commits may be relicensed if the new license still allows me to use the code, let me know if this requires me to sign anything.

I was also curious how much other people have actually contributed to anything substantial. @PredaaA and @jack1142 and I are the only people to have contributed new functionality, the remainder of PRs people made are bug fixes and probably aren't protected as being a separate idea (still talk to the lawyer, I don't want you getting in trouble over this)

**Comment by mikeshardmind** [comment]
Until this is settled in any fashion, to keep things simple I'm not going to be accepting new PRs.

**Comment by mikeshardmind** [comment]
#227 has the form of license currently under consideration.

**Comment by Jackenmen** [comment]
> My commits may be relicensed if the new license still allows me to use the code

Same for me here. As said in Discord though, I want to suggest (if possible) having a license that doesn't require developers to disclose source (i.e. like (A)GPL).

**Comment by mikeshardmind** [comment]
The new license was merged after more talk about this
