### ISSUE TITLE
[ModOnlyMode] Allow excluding some commands from this permissions hook.

### ISSUE THREAD

**Issue by DiscordLiz** [mikeshardmind/SinbadCogs#233]
**Is your feature request related to a problem? If so, Please describe.**

Permissions is hard to use in complex ways without hooks.

**Describe the solution you'd like**

Adding a way to just exclude a few commands from this hook would make it a more useful hook.

**Describe alternatives you've considered if any**

None

**Additional context**
Also, there's other demand for this capability.
![image](https://user-images.githubusercontent.com/47602820/87722985-0f559200-c787-11ea-8840-7234bb197c66.png)

**Comment by mikeshardmind** [comment]
The only thing that has to be kept in mind for this is avoiding the conditions for [this upstream issue with permission hooks](https://github.com/Cog-Creators/Red-DiscordBot/pull/3956)
