### ISSUE TITLE
[RoleManagement] Variation Handling

### ISSUE THREAD

**Issue by DiscordLiz** [mikeshardmind/SinbadCogs#239]
You need to compare using the regex here
https://github.com/mikeshardmind/SinbadCogs/blob/f2f4a6e03e6b2d4e84eadc42dbe8fb916bdbdedb/rolemanagement/core.py#L326

And possibly add a selector here?
https://github.com/mikeshardmind/SinbadCogs/blob/f2f4a6e03e6b2d4e84eadc42dbe8fb916bdbdedb/rolemanagement/core.py#L329

There's more than this. How do you want to handle it to not mess up the config?

**Comment by mikeshardmind** [comment]
I'll look at it later, but this probably means pulling the logic in from devtools for this too.

**Comment by mikeshardmind** [comment]
*sigh* I don't like a lot about this. I'm probably just going to add a warning to users if I detect these conditions in it because the alternative involves leaving an emoji that does not look right active for mobile users without being clear about what happened to cause that.
