### ISSUE TITLE
[Scheduler] API/Cog Integration

### ISSUE THREAD

**Issue by flaree** [mikeshardmind/SinbadCogs#250]
**Is your feature request related to a problem? If so, Please describe.**
Ability to be able to integrate a cog with scheduler to schedule multiple events with ease. 

**Describe the solution you'd like**
An API/ way to hook into schedule to schedule events. 

**Describe alternatives you've considered if any**
I tried manually integrate how schedule parses it however I was scheduling up to 5 events at once so they had all got the same ID and thus after a restart only the last one would remain

**Additional context**
N/a

**Comment by mikeshardmind** [comment]
Won't be doing this immediately, however here's the idea:

1. one special attr on the cog

`__public_api_methods__`: a dict of string to int represneting the methods and a version which will be used if the behavior or signature change (allows detecting if it's compatible with expectations)

2. A method that lets you schedule a command, returning a token
3. A method that lets you cancel something you programmatically scheduled by providing the token.

Don't really want anything directly messing with my storage on this, but the above way would be fine.

**Comment by mikeshardmind** [comment]
I went with a slightly different approach on the variables you can check for what's supported.

```py
    __external_api_version__ = 1
    __external_supported_api__ = ("api_schedule", "api_unschedule")
```

I'm not creating docs for this right now, but the functions I'm willing to support external use on here are documented well enough for real use.
