### ISSUE TITLE
Embedmaker Global Perms

### ISSUE THREAD

**Issue by Kreusada** [mikeshardmind/SinbadCogs#251]
**Is your feature request related to a problem? If so, Please describe.**
Users with normal permissions cannot use global embeds in different servers.

**Describe the solution you'd like**
For anyone to be able to [p]globalembedcommand, in any server.

**Additional context**
I want the ability for my bot to give anyone, in any server, access to seeing embeds by using [p]globalembedcommand.
Currently this is not do-able.

**Comment by mikeshardmind** [comment]
Sounds reasonable for the drop command, but not for dm or creation. I'll make a tweak a little later tonight.

**Comment by mikeshardmind** [comment]
resolved by 408e957bfb29ec567a2cbd957778c75b11820a06
