### ISSUE TITLE
Invocation of Grandfather Provision

### ISSUE THREAD

**Issue by Zephyrkul** [mikeshardmind/SinbadCogs#258]
As per section 6 of your License: https://github.com/mikeshardmind/SinbadCogs/blob/v3/LICENSE#L124-L148

I am requesting that all commits of mine on this repository be removed.

**Comment by mikeshardmind** [comment]
Done. Do note that if you want this removed in forks, you'll need to contact each person who has forked the repo or ask GitHub support for assistance.

**Comment by Zephyrkul** [comment]
Thank you.
