### ISSUE TITLE
General Question About EmbedMaker

### ISSUE THREAD

**Issue by Jacob-1999** [mikeshardmind/SinbadCogs#259]
Hey Sinbad;

I have a question about your embedmaker cog. Do you support the `content:` variable? It would be nice to be able to have messages outside of an embed for things like important notes or to @mention a user/role with the embed listing whatever information is needing a ping.

I'd happily sponsor this change if possible in the future.

**Comment by mikeshardmind** [comment]
I'm not currently considering further changes to any code here. The code remains available to not have my decisions relating to leaving Red break people who have not switched to supported alternatives, whether they be in the red ecosystem or not.

**Comment by Jacob-1999** [comment]
That's unfortunate. I hope you're doing well and I did enjoy your cogs. Enjoy 2021
