### ISSUE TITLE
[Autorooms] makeclone does not check for valid channels or duplicates

### ISSUE THREAD

**Issue by HelmicNewciv** [mikeshardmind/SinbadCogs#26]
!autoroomset makeclone does not check to see if the channel actually exists or if it's already been cloned.  It should check first to see if the room exists, and if not it should return a message explaining how to get the channel ID of a voice channel (User Setings -> Appearance -> Under Advanced, turn on Developer Mode, then right click a channel and click Copy ID).  If it's already been cloned, it should either remove that clone (solving #25 ) or otherwise return an error message.

**Comment by mikeshardmind** [comment]
I should have time to get this part put together at some point today.

**Comment by mikeshardmind** [comment]
Checks added.
