### ISSUE TITLE
Whiny message about "I was removed from Red" still exists, despite no longer having this repo installed.

### ISSUE THREAD

**Issue by Jatts-Art** [mikeshardmind/SinbadCogs#261]
Your stupid drama message keeps spamming me every single time I turn on Red V3, despite no repos belonging to you being installed anymore. I even went into the directories and deleted all the folders too, and it still pops up every time. Fix ur SHIT!

![a3288822ee4499861671f1a722eef388](https://user-images.githubusercontent.com/12752293/111581762-3d64f900-8790-11eb-8689-470b67041301.png)

**Comment by mikeshardmind** [comment]
This is flat-out not possible. If you don't have the cogs installed, this can not be caused by any of the code here.
