### ISSUE TITLE
Logger usage bug reported by MyPy PR

### ISSUE THREAD

**Issue by henryiii** [mikeshardmind/SinbadCogs#262]
In https://github.com/python/typeshed/pull/5849, something was exposed that looks like a bug:

```
SinbadCogs (https://github.com/mikeshardmind/SinbadCogs.git)
+ anticommandspam/core.py:80: error: Unexpected keyword argument "user_id" for "info" of "Logger"
```

If this is a a normal logger, this is the wrong syntax at https://github.com/mikeshardmind/SinbadCogs/blob/ebf7b44436a8db877151836c6fcb394445fb3c5b/anticommandspam/core.py#L80-L84 .

```pycon
>>> import logging
>>> author_id = 2
>>> log.info(
...        "User: {user_id} has been blocked temporarily for "
...        "hitting the global ratelimit a lot.",
...        user_id=author_id,
...    )
>>> log.setLevel(logging.INFO)
>>> log.info(
...     "User: {user_id} has been blocked temporarily for "
...     "hitting the global ratelimit a lot.",
...     user_id=author_id,
... )
```
```pytb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/__init__.py", line 1446, in info
    self._log(INFO, msg, args, **kwargs)
TypeError: _log() got an unexpected keyword argument 'user_id'
```

This is the correct syntax:

```pycon
>>> log.warning(
...     "User: %(user_id)s has been blocked temporarily for "
...     "hitting the global ratelimit a lot.",
...     {"user_id":author_id},
... )
```

While I'd like `format` syntax to have been valid, logger is much older than `format`. I'm guessing if you actually enable INFO log printing, this breaks?

**Comment by mikeshardmind** [comment]
Thanks for reaching out on this. It's a `{` style logging formatter, (not visible here as this is an extension to other code not in this repository and attaches to an existing logger) but it's still invalid currently. I'll add a commit fixing this
