### ISSUE TITLE
[Autorooms] Customize naming scheme

### ISSUE THREAD

**Issue by HelmicNewciv** [mikeshardmind/SinbadCogs#27]
A command to customize the name of the cloned channels would be nice.  You could include (original) for the original channel name, (user) for the name of the user that created the auto chanel, (#) for the lowest unused number for that cloned channel (so people can specify rooms as Overwatch #1, Overwatch #3, Overwatch #2, et cetera), et cetera.

**Comment by mikeshardmind** [comment]
I'd like to add this in the future, but it will depend on how soon I can commit the time as to when this is added.

**Comment by HelmicNewciv** [comment]
If I can help, let me know.

A way to automatically name the room based on what game most people or the creator is playing would be helpful too.  Having used this for a little while, I noticed a lot of people will try to rename the room to whatever it is they're doing as a sort of open invitation for others to join in.  Seeing "Factorio" would quickly communicate to everyone what the four people are doing in that one channel.  Other times they're using Red as a community jukebox, so having a music symbol going to denote that would let people know what's going on before going in.

**Comment by mikeshardmind** [comment]
I may add more ways to customize this further later, but there should be enough customization options available to meet the use cases presented.

**Comment by HelmicNewciv** [comment]
The game names are definitely helpful even if it's a bit clunky to need to have a game running first, knowing what people are actually doing in a channel helps a lot in getting other interested people to join in.
