### ISSUE TITLE
[Autorooms] Give user full permissions

### ISSUE THREAD

**Issue by HelmicNewciv** [mikeshardmind/SinbadCogs#28]
It would be helpful to have a command to make a cloned channel give the user that created it full permisions.  On a busy server, this would allow users to essentially create their own channels and be able to mute and deafen others, change the bitrate, restrict access to only their friends, send links directly to that voice channel so that their friends don't have to find it in a busy server, and otherwise do as they please.  This makes it unnecessary for users to create their own server just for voice chat, this keeps users in the server and engaged with the community.

It is possible in Discord to allow users to create channels, of course, but this would have the added benefit of cleaning up unused channels and avoiding clutter and prevents a single user from creating more than one channel at a time.

**Comment by mikeshardmind** [comment]
I'll add this as a toggle setting in the next version.

**Comment by mikeshardmind** [comment]
Added.

**Comment by HelmicNewciv** [comment]
Awesome!  Slight problem, though, in that you can't specify which channel ID's you want ownership to apply to.  It's definitely useful for my servers, though, everything's much tidier.
