### ISSUE TITLE
[streamannouncer] Restrict announcements to only those with a certain game playing

### ISSUE THREAD

**Issue by HelmicNewciv** [mikeshardmind/SinbadCogs#35]
For larger servers centered around a single game, it'd be nice to be able to announce when someone is streaming that game without announcing when someone is streaming just any 'ole game.  Could be combined with the role restrictions to have it so only certain streamers the devs wish to promote will show up.

**Comment by mikeshardmind** [comment]
Not a super high priority on my todo list. If someone PR's an addition that does this, I'll be more than happy to pull it, otherwise this is most likely going to have to wait until I have a bit more time.

**Comment by mikeshardmind** [comment]
I'll be taking a look at the twitch API docs later to look for a good way to go about doing this.

**Comment by mikeshardmind** [comment]
This won't be in the current version, but when I release a version for red v3, it will be

**Comment by mikeshardmind** [comment]
obsoleted for V3 by core red functionality.
