### ISSUE TITLE
[streamannouncer] Delete messages when stream goes offline

### ISSUE THREAD

**Issue by HelmicNewciv** [mikeshardmind/SinbadCogs#36]
By default, it seems like Red's built-in stream cogs will delete the post once the stream goes offline, which is useful when posting the stream in the main chat channel since it keeps someone's spotty connection from spamming the chat.  It'd be nice to have it here too, at least as an option.

**Comment by mikeshardmind** [comment]
This is not a top priority for me. If someone PR's an addition that does this, I'll be happy to pull it after some testing, otherwise this is going to be on the back burner for a bit.

**Comment by mikeshardmind** [comment]
Will be added in the version of the cog for v3

**Comment by mikeshardmind** [comment]
This may end up not being a cog anymore, and may end up in the core functionality of Red in v3. Awaiting a bit more information before I start migrating this.

**Comment by mikeshardmind** [comment]
This will be obsoleted by functionalities on core red. Closing this.
