### ISSUE TITLE
[ReportTool] Error when attempting to send reports in DM's

### ISSUE THREAD

**Issue by HelmicNewciv** [mikeshardmind/SinbadCogs#37]
Currently, when I go to use the report tool in a DM, it instead throws an error.

```
[16/09/2017 15:56] ERROR red on_command_error 369: Exception in command 'report'
Traceback (most recent call last):
  File "lib/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/jimsterling/cornflake-homunculus/cogs/reporttool.py", line 97, in                                                                                                                                                              makereport
    if server.id not in self.settings:
AttributeError: 'NoneType' object has no attribute 'id'
```

This works fine when using !report in the server itself, as the bot can tell which server is supposed to receive the report.

My users need a way to discretely send a report to all moderators/admins as we sometimes deal with sensitive stuff, so DM'ing the command is the safest method (no worrying about the bot temporarily going offline and not deleting the command before anyone can see it).  If they're seen submitting a report, that could mark them for harassment from whoever's going on a bigoted rant.

It's probably possible to check what servers the bot shares with the user DM'ing them and then asking the user to specify what server to send the report to if there's more than one (whether or not ReportTools is enabled on all those servers, just to be extra safe).

**Comment by mikeshardmind** [comment]
Ugh, yeah... I can add a way to do that. I know what the issue is with that, it was me being lazy in implementing it.

**Comment by mikeshardmind** [comment]
Added a quick interactive prompt for selecting from shared servers if initiated via DM 

d76af53
