### ISSUE TITLE
[IDEA] Suggestion for Multiwayrelay/Linkchannel cog

### ISSUE THREAD

**Issue by curryandrice** [mikeshardmind/SinbadCogs#40]
If possible could the messages be relayed using webhooks? so it appears as if the user posted themselves rather than the bot quoting.

Also a toggle that allows attachments and links to embed like normally.

**Comment by mikeshardmind** [comment]
I would rather not rely on webhooks as this bloats the required permissions without any significant gain, it will also make the messages appear to be broken if people are not 100% aware of how this is functioning as they will be unable to properly click the webhook to message (and other things specific to users) without it being immediately clear why. This is not intended to have the bot impersonate users, just pass their message along.
