### ISSUE TITLE
timestamp in embeds

### ISSUE THREAD

**Issue by NNTin** [mikeshardmind/SinbadCogs#41]
Love your crossquote cog. Unfortunately it does not post the timestamp in localized time. [Discord does support localized timestamps.](https://discordapp.com/developers/docs/resources/channel#embed-object)

Currently the timestamp is passed as a string to the footer object. With the change people on different timezones will see the correct time and don't have to do any time conversion.

**Comment by mikeshardmind** [comment]
Thank you for pointing me at that, I hadn't realized at first glance that the timestamp object in embeds wasn't the same as the message timestamp.
