### ISSUE TITLE
[announcer] All X times

### ISSUE THREAD

**Issue by THEDARKK** [mikeshardmind/SinbadCogs#42]
Hello, I would like to know if it is possible to add a message x time in the channels?
Thank you

**Comment by mikeshardmind** [comment]
Do you mean to send multiple messages, or to schedule a message for a specific time?

**Comment by THEDARKK** [comment]
Put a message every 10 minutes for example.
Thank you

**Comment by mikeshardmind** [comment]
I have no intention of adding this functionality directly into the cog, but you could use an existing solution for scheduling commands ([found here](https://github.com/tekulvw/Squid-Plugins/blob/master/scheduler/scheduler.py)) in Red.
