### ISSUE TITLE
[IDEA] One way relay

### ISSUE THREAD

**Issue by RespectWomen** [mikeshardmind/SinbadCogs#49]
Maybe as a feature in multiwayrelay cog, I'd like for messages to go to another channel without receiving any back from it.

**Comment by mikeshardmind** [comment]
I removed the one way version from the repo a while ago, but still had the code. It is in the unsupportedv2 branch if you wish to use it. As the name of that branch suggests, there will not be any attempt at fixing any problems discovered with the code in that branch, use at your own risk.
