### ISSUE TITLE
[TempChannels] save previous channel settings, channel categories

### ISSUE THREAD

**Issue by GGrandma** [mikeshardmind/SinbadCogs#51]
I was wondering if this could be added or if it’s possible but what I was thinking is if a user changes for example the user limit on there temporary channel that even after the channel is deleted the next time they go to get there temporary channel back that the bot will automatically set the user limit to what is was previously. Also a option to put all temporary channels under a set category. Example: Admin could confingure the catigory with [p]tempchannel category categories name) and this can be toggled on and off.

**Comment by mikeshardmind** [comment]
Category support to be added soon.

**Comment by mikeshardmind** [comment]
012bcd8 adds category support. I am not planning to add the ability to have saved temporary channel settings right now, but this may change at a later date.
