### ISSUE TITLE
[reporttool] Failed reports trigger a cooldown timer

### ISSUE THREAD

**Issue by HelmicNewciv** [mikeshardmind/SinbadCogs#55]
So someone was receiving death threats and tried to use the report tool - but since they hadn't used it before, they didn't know about needing to use a number to specify the server.  Since there's only one server the bot is on, I think the prompt to specify a number should only come up if the bot is part of multiple servers.  If possible, the bot should only show the prompt if the user is actually part of multilpe mutual servers with the bot AND if the user DM'd the !report command (since if you typed it in the server itself, we can infer that they probably wanted the report sent to that server).

What ended up happening was that since they took too long to put in a number, the tool told them they took too long and to try again later - and then wouldn't let them submit another report.  The countdown for sending that number also seems really really short.

Considering that if someone really wanted to be annoying with the report tool they can just be banned, I think at least it should be configurable how long the delay is between reports, if there should be a delay at all.  And if a report fails, it should be posisble to immediately send a new report, only successful reports should trigger the cooldown timer if it exists.

Luckily it panned out that the dude sending the death threats stormed off and I could just ban them when I happened to glance at the chat half an hour later, but obviously it's kind of an issue if someone who isn't familiar with the tool has to wait several minutes between report attempts when there's a serious issue requiring immeidate attention.

**Comment by HelmicNewciv** [comment]
It also seems some people assume the usage is !report <message>, so having that as an option would help reduce the potential for confusion.

**Comment by mikeshardmind** [comment]
Adding this to this weekend's todo list.

**Comment by mikeshardmind** [comment]
I've handled the failed reports triggering a cooldown in 68183c6 , the other functionality (`!report [message]`) is something to be implemented in the v3 version of the cog.
