### ISSUE TITLE
[V3] Relay : List the server channels belong to

### ISSUE THREAD

**Issue by Ray-Killer** [mikeshardmind/SinbadCogs#76]
I'd be nice for it to state what server it's linked to, as right now it's very confusing trying to remember what servers are linked to a channel. 
![image](https://user-images.githubusercontent.com/10146271/40874575-f8f1d55e-6668-11e8-8ec2-1e74b13c4871.png)
as that isn't very helpful if you've got multiple servers connected to a channel and doesn't state what's connected.

**Comment by mikeshardmind** [comment]
Putting this on the todo list

**Comment by mikeshardmind** [comment]
Implemented.
