### ISSUE TITLE
[V3] Relay : Respect filter & remove inv links

### ISSUE THREAD

**Issue by Ray-Killer** [mikeshardmind/SinbadCogs#77]
is it possible for the filter to work with relay? globally? 
it'd prevent profanity ect and possibly invite links? ik it's a bit much but relays used globally would benefit a lot from this

**Comment by mikeshardmind** [comment]
I have not forgotten about this, but I should have marked Cog-Creators/Red-DiscordBot#1873 as something this is waiting to see what it brings first.

**Comment by mikeshardmind** [comment]
Above issue is stale. I'll likely add this in in a single commit later which can be reverted with changes to use builtin things later.

**Comment by mikeshardmind** [comment]
@Ray-Killer Cog-Creators/Red-DiscordBot#1873 seems stale at this point, and I'd rather not leave you waiting indefinitely on this. I'll be adding a couple extra global settings to for use to cover this.

**Comment by mikeshardmind** [comment]
f0dfde1 added link scrubbing, filter object handling still to be done later.

**Comment by mikeshardmind** [comment]
Filter object handling is still waiting on WIP stuff to the core mod cog.

**Comment by DiscordLiz** [comment]
@mikeshardmind Is this still waiting on something specific, if so, what?

**Comment by mikeshardmind** [comment]
I misspoke slightly. Not waiting on something in mod, but in filter. 

Specifically, this is currently waiting on the PR which improves the filter performance https://github.com/Cog-Creators/Red-DiscordBot/pull/2509. I don't want to add this in and incur the current performance hit per message per destination forwarded to. The reduced performance hit will be acceptable as an additional setting.

Previously it was waiting on something else, but that's the last blocker on that.

**Comment by DiscordLiz** [comment]
Is this waiting also now waiting on the Filter API or can I have this fetch the filter?

**Comment by mikeshardmind** [comment]
Let's wait on the API and do it right.

**Comment by mikeshardmind** [comment]
[Won't be added](https://github.com/mikeshardmind/SinbadCogs/blob/v3/why_no_support.md)
