### ISSUE TITLE
V3 Role Management

### ISSUE THREAD

**Issue by mikeshardmind** [mikeshardmind/SinbadCogs#83]
Here's a list of things this has planned, and the status of each

- [X] Role criteria
- [X] Role searches
- [X] Self Role assignment by command
- [X] Self Role assignment by reactions 
- [X] Mass Role assignment with criteria
- [x] Per user forbidden role settings (prevent specific users from gaining a role)

**Comment by mikeshardmind** [comment]
With #87 finished, The remaining tasks here are going to be significantly easier to finish work on without introducing errors.

Reaching out to various parties on what they would want to see for automatic role assignment criteria along with a few things of my own based on time in server + activity levels in server.

**Comment by mikeshardmind** [comment]
I've not found a clean way to handle the hidden role part yet. I have a couple more things I can explore with that later tonight, but that particular part might be something handled later.

I'm starting work on the conditional automatic role grant tonight.

**Comment by mikeshardmind** [comment]
@HelmicNewciv 

Here's the current plan for handling automatic role grant:

Upon reaching any combination of the below criteria set:

Number of qualifying messages*
Amount of time in server
Amount of time spent in voice chat (niche, but easy enough to add, and has been asked for)

Qualifying messages can have a minimum length, channel restrictions, as well as a maximum amount of them that can qualify in a period (to prevent spam -> role).

I'm looking to ensure this gets cleaned up and finished prior to a stable release of version 3 of Red, so sooner than later, but since I've been helping with that push as well, I have spent less time than I originally intended on this.

**Comment by HelmicNewciv** [comment]
That looks good!  Just to be sure, will there be a way to blacklist individual users before they meet any of those requirements?  Being able to spot and mark problematic users ahead of time would keep them from accessing sensitive channels without outright banning them altogether.

**Comment by HelmicNewciv** [comment]
I suppose the other feature that would be nice is a way to DM the user first and have them agree to rules before gaining access.  But then I start thinking about just wanting a general way to use these sorts of filters for other moderation-related or memey tasks.  I believe there were concerns about performance issues for making this sort of functionality part of core?

**Comment by mikeshardmind** [comment]
1daea75 Just ticked off the ability to forbid a user from self-assigning a role (or from gaining it via earned role criteria) I'm considering adding an additional stricter setting which would also prevent mods from adding that role to that user, but I'm trying to keep this cog from clogging bot events too, so I'l;l have to give that a bit more thought.

**Comment by mikeshardmind** [comment]
@HelmicNewciv I have a working implementation of the criteria roles, but it's going to need rewriting some parts to avoid some really draining performance considerations. likely won't be available for a bit, as I'm going to prioritize a few other cogs over implementing this feature.

**Comment by mikeshardmind** [comment]
I'm marking this as done (for now).

The remaining features can all be added in the future without the need to call this a beta.
