### ISSUE TITLE
V3 Automoderation

### ISSUE THREAD

**Issue by mikeshardmind** [mikeshardmind/SinbadCogs#84]
I'll be starting work on an automod cog after the main things from #57 are finished.

Here are the planned features so far, I know it's a little generalized.

Automatic scanning of messages, with flagging for mod review.
Training mode: for each message, the bot will generate what it thinks the correct action (including choosing not to act is)

This cog should also be aware of the following things:

Command usage vs messages
Permissions / administrative roles

The cog will learn on the fly if used that way, but will also learn in a training mode if used that way.

**Comment by Brandjuh** [comment]
I would really love this.

**Comment by mikeshardmind** [comment]
This is going on the backburner for a little bit while I explore some better options for other cogs first.

**Comment by mikeshardmind** [comment]
Closing this, this will not be completed as a cog for Red.
