### ISSUE TITLE
roleblacklist.py issue

### ISSUE THREAD

**Issue by Note2Self** [mikeshardmind/SinbadCogs#85]
Hi I'm getting an error with the roleblacklist.py cog this is the error 

`File "C:\Users\Carl\Documents\bot\cogs\roleblacklist.py", line 61, in <genexpr>
    for r in author.roles
KeyError: '465536300452151298'`

@mikeshardmind

**Comment by Note2Self** [comment]
I believe that the KeyError: is my server ID

**Comment by mikeshardmind** [comment]
@Note2Self This is fixed as of 7bc0cf5
